### ISSUE TITLE
圆形控件初次渲染会有报错，个性化地图功能有BUG

### ISSUE THREAD

**Issue by YaoBoWen1** [Dafrok/vue-baidu-map#1004]
### 浏览器版本号

谷歌浏览器 版本 104.0.5112.81（正式版本） （64 位）

### Vue 版本号

vue2.0

### 组件库版本号

0.21.22

### 现象描述

```
bm-circle圆形控件editing初始值就为true的话，会报错一个foreach方法遍历的值不存在，查看源码发现是circle组件里的bindEditingNodeEvents方法值为undefined，个性化地图功能目前V2的链接不满足需求mapStyle方法有问题会出现大量空白块，是否可以升级下V3链接使用mapstyleV2呢
```

### 完整异常信息

```
Uncaught TypeError: Cannot read properties of undefined (reading 'forEach')
    at a.bindEditingNodeEvents (main.c0485a48.bundle.js:1:173392)
    at n (libs.c0485a48.bundle.js:6:1053)
    at a.enableEditing (main.c0485a48.bundle.js:1:173579)
    at n (libs.c0485a48.bundle.js:6:1053)
    at main.c0485a48.bundle.js:1:174465
```

### 在线示例 / 仓库 URL

https://dafrok.github.io/vue-baidu-map/#/zh/overlay/circle

### 复现用例

```
https://dafrok.github.io/vue-baidu-map/#/zh/overlay/circle
```

### 预期输出

```
预期正常渲染不报错
```

### 实际输出

```
实际会有一个报错
```

**Comment by y0lo-0924** [comment]
想问一下如何解决的

**Comment by zsy77** [comment]
请问有解决办法吗
