### ISSUE TITLE
关于使用v-for增加覆盖物的问题

### ISSUE THREAD

**Issue by ahugeStone** [Dafrok/vue-baidu-map#30]
下面代码如果放开注释部分浏览器会报错，如果v-for部分的pointList不变化，或者不添加bm-navigation都没问题，两者共存就报错了。
```vue
<template lang="html">
<baidu-map :center="BDMap.center" @ready="handler" :zoom="BDMap.zoom" class="bm-view">
    <bm-marker
    v-for="point in pointList"
    :position="{lng: point.lng, lat: point.lat}">
    </bm-marker>
    <!-- 以下部分放开会报错 -->
    <!-- <bm-navigation anchor="BMAP_ANCHOR_TOP_RIGHT" />
    <bm-geolocation anchor="BMAP_ANCHOR_BOTTOM_RIGHT" :showAddressBar="true" :autoLocation="true"/> -->
</baidu-map>
</template>

<script type="text/javascript">
export default {
  data() {
    return {
      BDMap: {
        center: {
          lng: 116.404,
          lat: 39.955
        },
        zoom: 12
      },
      pointList: [{
        lng: 116.414,
        lat: 39.915,
      }, {
        lng: 116.424,
        lat: 39.915,
      }]
    }
  },
  methods: {
    handler() {
      this.pointList.push({
        id: 1,
        lng: 116.524,
        lat: 39.955
      })
    }
  }
}
</script>

<style scoped>
.bm-view {
    width: 100%;
    height: 300px;
}
</style>
```

chrome报错如下
```
vue.esm.js?65d7:467 DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Object.insertBefore (eval at <anonymous> (http://localhost:2001/app.js:810:1), <anonymous>:4407:14)
    at insert (eval at <anonymous> (http://localhost:2001/app.js:810:1), <anonymous>:4713:17)
    at createElm (eval at <anonymous> (http://localhost:2001/app.js:810:1), <anonymous>:4643:7)
    at VueComponent.patch [as __patch__] (eval at <anonymous> (http://localhost:2001/app.js:810:1), <anonymous>:5054:7)
    at VueComponent.Vue._update (eval at <anonymous> (http://localhost:2001/app.js:810:1), <anonymous>:2034:19)
    at VueComponent.updateComponent (eval at <anonymous> (http://localhost:2001/app.js:810:1), <anonymous>:2157:10)
    at Watcher.get (eval at <anonymous> (http://localhost:2001/app.js:810:1), <anonymous>:2468:25)
    at new Watcher (eval at <anonymous> (http://localhost:2001/app.js:810:1), <anonymous>:2451:12)
    at mountComponent (eval at <anonymous> (http://localhost:2001/app.js:810:1), <anonymous>:2161:17)
    at init (eval at <anonymous> (http://localhost:2001/app.js:810:1), <anonymous>:2930:13)
logError @ vue.esm.js?65d7:467

```

**Comment by Dafrok** [comment]
不要用自闭合标签

**Comment by ahugeStone** [comment]
像下面这样改过之后还是有问题，貌似和自闭合无关
```vue
<baidu-map :center="BDMap.center" @ready="handler" :zoom="BDMap.zoom" class="bm-view">
    <bm-marker
    v-for="point in pointList"
    :position="{lng: point.lng, lat: point.lat}">
    </bm-marker>
    <bm-navigation anchor="BMAP_ANCHOR_TOP_RIGHT"></bm-navigation>
    <bm-geolocation anchor="BMAP_ANCHOR_BOTTOM_RIGHT" :showAddressBar="true" :autoLocation="true"></bm-geolocation>
</baidu-map>
```

**Comment by Dafrok** [comment]
这是由于 vue 在渲染 list 时会把 DOM Element 插入父元素的末尾造成的，这个 bug 已列入修复计划内，先给你提供一个临时的解决办法，把 `bm-marker` 在末尾声明，或者套一个 wrapper，如下：

```vue
<baidu-map :center="BDMap.center" @ready="handler" :zoom="BDMap.zoom" class="bm-view">
    <bm-navigation />
    <bm-geolocation />
    <bm-marker v-for="point in pointList" :position="{lng: point.lng, lat: point.lat}">
    </bm-marker>
</baidu-map>
```

```vue
<baidu-map :center="BDMap.center" @ready="handler" :zoom="BDMap.zoom" class="bm-view">
    <div>
        <bm-marker v-for="point in pointList" :position="{lng: point.lng, lat: point.lat}">
        </bm-marker>
    </div>
    <bm-navigation />
    <bm-geolocation />
</baidu-map>
```

**Comment by ahugeStone** [comment]
已解决，谢谢

**Comment by Dafrok** [comment]
@ahugeStone 0.3.7 版本发布，已修复这个问题，可以不用考虑节点顺序了。
