### ISSUE TITLE
按需引入组件报错

### ISSUE THREAD

**Issue by ouyangxiaoai** [Dafrok/vue-baidu-map#304]
### 浏览器版本号

chrome 63

### Vue 版本号

2.4.2

### 组件库版本号

0.20.7

### 现象描述

```
已经按需引用了element-ui，所以babel的配置已经改过。除了BaiduMap和BmView即components下的两个文件可以正常引入，其它vue引入报错，如Scale.vue
```

### 完整异常信息

```

 error  in ./node_modules/vue-baidu-map/components/controls/Scale.vue

Module build failed: Error: Invalid mapping: {"generated":{"line":1,"column":0},"source":"Scale.vue","original":{"line":0,"column":0},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (E:\work\iot-website\node_modules\vue-loader\node_modules\source-map\lib\source-map-generator.js:298:13)
    at SourceMapGenerator_addMapping [as addMapping] (E:\work\iot-website\node_modules\vue-loader\node_modules\source-map\lib\source-map-generator.js:110:12)
    at generated.split.forEach (E:\work\iot-website\node_modules\vue-loader\lib\parser.js:45:11)
    at Array.forEach (native)
    at generateSourceMap (E:\work\iot-website\node_modules\vue-loader\lib\parser.js:43:28)
    at module.exports (E:\work\iot-website\node_modules\vue-loader\lib\parser.js:16:27)
    at Object.module.exports (E:\work\iot-website\node_modules\vue-loader\lib\loader.js:108:17)

 @ ./node_modules/babel-loader/lib?{"plugins":[["component",[{"libraryName":"element-ui","styleLibraryName":"theme-chalk"}]]],"babelrc":false,"cacheDirectory":true,"presets":["E://work//iot-website//node_modules//babel-preset-vue-app//dist//index.common.js"]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/us/link-us.vue 74:0-66
 @ ./pages/us/link-us.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=3000&path=/__webpack_hmr ./.nuxt/client.js
```

### 在线示例 / 仓库 URL

无法提供在线

### 复现用例

```
除了那两个只要分别引入组件就会报错
```

### 预期输出

```
可以成功按需引入所以组件
```

### 实际输出

```
报错
```

**Comment by Dafrok** [comment]
https://github.com/Dafrok/vue-baidu-map/issues/304

如果你急用的话可以参考一下这个
