### ISSUE TITLE
internet explorer 11 syntax error

### ISSUE THREAD

**Issue by hst0305** [Dafrok/vue-baidu-map#380]
### 浏览器版本号

internet explorer 11.431.16299.0

### Vue 版本号

2.9.3

### 组件库版本号

^0.21.10

### 现象描述

```
Using local registration components
Running app and accessing url:http://localhost:8080/: "syntax error"
```

### 完整异常信息

```
Development model
npm run dev
"syntax error"
app.js (1964,1)
eval("/* harmony import / var WEBPACK_IMPORTED_MODULE_0__events_js = webpack_require("./node_modules/vue-baidu-map/components/base/events.js");\n/ harmony import / var WEBPACK_IMPORTED_MODULE_1__util_js = webpack_require("./node_modules/vue-baidu-map/components/base/util.js");\n\n\n\n/ harmony default export / webpack_exports["a"] = (function (instance, eventList) {\n const ev = eventList || WEBPACK_IMPORTED_MODULE_0__events_js["a" / default /][Object(WEBPACK_IMPORTED_MODULE_1__util_js["b" / toKebabCase */])(this.$options._componentTag)]\n ev && ev.forEach(event => {\n const hasOn = event.slice(0, 2) === 'on'\n const eventName = hasOn ? event.slice(2) : event\n const listener = this.$listeners[eventName]\n listener && instance.addEventListener(event, listener.fns)\n })\n});\n//# sourceURL=[module]\n//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiLi9ub2RlX21vZHVsZXMvdnVlLWJhaWR1LW1hcC9jb21wb25lbnRzL2Jhc2UvYmluZEV2ZW50LmpzLmpzIiwic291cmNlcyI6WyJ3ZWJwYWNrOi8vLy4vbm9kZV9tb2R1bGVzL3Z1ZS1iYWlkdS1tYXAvY29tcG9uZW50cy9iYXNlL2JpbmRFdmVudC5qcz8xZTkzIl0sInNvdXJjZXNDb250ZW50IjpbImltcG9ydCBldmVudHMgZnJvbSAnLi9ldmVudHMuanMnXG5pbXBvcnQge3RvS2ViYWJDYXNlfSBmcm9tICcuL3V0aWwuanMnXG5cbmV4cG9ydCBkZWZhdWx0IGZ1bmN0aW9uIChpbnN0YW5jZSwgZXZlbnRMaXN0KSB7XG4gIGNvbnN0IGV2ID0gZXZlbnRMaXN0IHx8IGV2ZW50c1t0b0tlYmFiQ2FzZSh0aGlzLiRvcHRpb25zLl9jb21wb25lbnRUYWcpXVxuICBldiAmJiBldi5mb3JFYWNoKGV2ZW50ID0+IHtcbiAgICBjb25zdCBoYXNPbiA9IGV2ZW50LnNsaWNlKDAsIDIpID09PSAnb24nXG4gICAgY29uc3QgZXZlbnROYW1lID0gaGFzT24gPyBldmVudC5zbGljZSgyKSA6IGV2ZW50XG4gICAgY29uc3QgbGlzdGVuZXIgPSB0aGlzLiRsaXN0ZW5lcnNbZXZlbnROYW1lXVxuICAgIGxpc3RlbmVyICYmIGluc3RhbmNlLmFkZEV2ZW50TGlzdGVuZXIoZXZlbnQsIGxpc3RlbmVyLmZucylcbiAgfSlcbn1cblxuXG5cbi8vLy8vLy8vLy8vLy8vLy8vL1xuLy8gV0VCUEFDSyBGT09URVJcbi8vIC4vbm9kZV9tb2R1bGVzL3Z1ZS1iYWlkdS1tYXAvY29tcG9uZW50cy9iYXNlL2JpbmRFdmVudC5qc1xuLy8gbW9kdWxlIGlkID0gLi9ub2RlX21vZHVsZXMvdnVlLWJhaWR1LW1hcC9jb21wb25lbnRzL2Jhc2UvYmluZEV2ZW50LmpzXG4vLyBtb2R1bGUgY2h1bmtzID0gMCJdLCJtYXBwaW5ncyI6IkFBQUE7QUFBQTtBQUFBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTtBQUNBO0FBQ0E7QUFDQTsiLCJzb3VyY2VSb290IjoiIn0=\n//# sourceURL=webpack-internal:///./node_modules/vue-baidu-map/components/base/bindEvent.js\n");


Production model
npm run build
"syntax error"
vendor.71ec08c9f90e8d6cdf03.js (17,50879)
export default function (instance, eventList) {
const ev = eventList || events[toKebabCase(this.$options._componentTag)]
ev && ev.forEach(event => { //Debugging program error points to here
const hasOn = event.slice(0, 2) === 'on'
const eventName = hasOn ? event.slice(2) : event
const listener = this.$listeners[eventName]
listener && instance.addEventListener(event, listener.fns)
})
}

```

### 在线示例 / 仓库 URL

nothing

### 复现用例

```
nothing
```

### 预期输出

```
nothing
```

### 实际输出

```
"syntax error"
```

**Comment by Dafrok** [comment]
抛出 syntax error，为什么没有说明是哪个 syntax

**Comment by hst0305** [comment]
const ev = eventList || events[toKebabCase(this.$options._componentTag)] 
ev && ev.forEach
-----
我试了一下。
const a = [];
a && a.forEach(function(item){}); 这个在ie11下就会出现语法错误！

const 改成 var 可以。

vue 本身不是就会处理这些兼容问题？？

**Comment by hst0305** [comment]
在ie11级以下版本。调用下面的setViewport。显示就现在问题！
let pointList = [];
for....{
let point = new BMap.Point(.....);
pointList.push(point);
}
BMap.setViewport(pointList);

通过point还有其它的方法调整Viewport不？

**Comment by Dafrok** [comment]
编译 es next 是 babel 的工作，和 vue 无关。

**Comment by zooeyking** [comment]
我也遇到了类似问题，最终找到了解决办法。首先  按照往上说的加babel-polyfill.   不起作用的话，进行下一步：
![image](https://user-images.githubusercontent.com/16650705/44000183-21a924bc-9e4e-11e8-9c10-6c974ba789b0.png)
把vue-baidu-map从node_modules中拿出来，拿到自己编写的components 中，再引入。
主要是因为 babel  默认不会编译   node_modules中的东西的   拿出来放到自己的组件中   就可以编译，IE就可以识别了。希望对你有帮助

**Comment by Dafrok** [comment]
bebel 是可以编译的，只要你指定了路径

**Comment by qm8956** [comment]
为啥https://dafrok.github.io/vue-baidu-map/#/用ie11打不开呢，我得项目再其他浏览器都好着呢，就时ie11报如下错误，babel-polyfill也已经引入
      stack: "SyntaxError: 语法错误
   at ./node_modules/vue-baidu-map/components/base/bindEvent.js (http://localhost:8080/3.js:281:1)
   at __webpack_require__ (http://localhost:8080/app.js:708:12)
   at fn (http://localhost:8080/app.js:113:13)
   at Anonymous function (eval code:5:22)
   at eval code (eval code:1:29)
   at ./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/vue-baidu-map/components/Map/Map.vue

**Comment by Dafrok** [comment]
让 babel 编译一下就行了，没有那么复杂

**Comment by ethan666** [comment]
使用现代模式编译就行了
vue-cli-service build --modern

https://cli.vuejs.org/zh/guide/browser-compatibility.html#%E7%8E%B0%E4%BB%A3%E6%A8%A1%E5%BC%8F
