### ISSUE TITLE
华为自带浏览器显示空白

### ISSUE THREAD

**Issue by JakeWoki** [Dafrok/vue-baidu-map#426]
### 浏览器版本号

4.0.158

### Vue 版本号

2.5.2

### 组件库版本号

0.21.10

### 现象描述

```
华为自带浏览器显示空白，UC、搜狗正常
```

### 完整异常信息
``` JavaScript
Use of const in strict mode.
at Object.webpackJsonp../node_modules/vue-baidu-map/components/base/bindEvent.js (http://192.168.0.14:8080/0.js:30:1)
at __webpack_require__ (http://192.168.0.14:8080/app.js:708:30)
at fn (http://192.168.0.14:8080/app.js:113:20)
at Object.eval ([module]:1:123)
at Object.eval ([module]:372:30)
at Object.webpackJsonp../node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modules/vue-baidu-map/components/map/Map.vue (http://192.168.0.14:8080/0.js:7:1)
at __webpack_require__ (http://192.168.0.14:8080/app.js:708:30)
at fn (http://192.168.0.14:8080/app.js:113:20)
at Object.eval ([module]:1:124)
at Object.webpackJsonp../node_modules/vue-baidu-map/components/map/Map.vue (http://192.168.0.14:8080/0.js:62:1)
```

`[vue-router] Failed to resolve async component default: SyntaxError: Use of const in strict mode.`

`[vue-router] uncaught error during route navigation:`

``` JavaScript
[WDS] Disconnected!
at Object.close ([module]:176:9)
at SockJS.onclose ([module]:17:16)
at SockJS.EventTarget.dispatchEvent ([module]:170:20)
at SockJS.eval ([module]:965:10)
```
```
暂无
```

### 在线示例 / 仓库 URL

```
<baidu-map class="bm-view" center="北京">
    <bm-view style="width: 100%; height:15rem"></bm-view>
  </baidu-map>
```
```
.bm-view {
    width: 100%;
    height: 100%;
  }
```
### 复现用例

```
暂无
```

### 预期输出

```
暂无
```

### 实际输出

```
暂无
```

**Comment by Dafrok** [comment]
看 console 吧，不是所有人都有华为手机的。估计八成是 polyfill 的问题

**Comment by JakeWoki** [comment]
另外文档是不是错了？
<baidu-map :center="center" :zoom="zoom" @ready="handler"></baidu-map>

[Vue warn]: Invalid handler for event "ready": got undefined found in <BmMap>

**Comment by Dafrok** [comment]
1. https://github.com/mrdulin/blog/issues/35
2. 看不出哪有问题

**Comment by wanqianjin** [comment]
我遇到这个问题 按照这个链接解决了！https://blog.csdn.net/qq_39963516/article/details/89673334?depth_1-utm_source=distribute.pc_relevant.none-task&utm_source=distribute.pc_relevant.none-task
