### ISSUE TITLE
低版本chrome不兼容

### ISSUE THREAD

**Issue by wekerSnail** [Dafrok/vue-baidu-map#463]
### 浏览器版本号

chrome44

### Vue 版本号

2.0

### 组件库版本号

"0.21.10"

### 现象描述

```
页面空白，代码报错
```

### 完整异常信息

```
代码语法错误
```

### 在线示例 / 仓库 URL

无

### 复现用例

```
使用低版本chrome内核，40+，插件使用局部注册的方式使用，使用编译过的index.js无错误
```

### 预期输出

```
局部注册兼容低版本chrome
```

### 实际输出

```
不兼容，报错，ps：建议官方加入polyfill兼容插件
```

**Comment by Dafrok** [comment]
polyfill **必须** 由开发者自己加。试想以下，每个库都整合一份 polyfill，你依赖 100 个包，就是 polyfill * 100 的体积。

**Comment by wekerSnail** [comment]
但是我项目中已经有加polyfill，并无效果，所以我觉得应该是的在插件源码那边加才行，我现在的困惑是，我如果在那边加了，并不能同步到代码管理，因为我不会上传node_module,那怎么保证其他人可以更新上呢？这边没有想到好的解决方法，我目前的处理方式是把插件中的components全拷贝到了项目中引入使用

**Comment by Dafrok** [comment]
polyfill 是全局生效的，加在库里没有任何意义。如果你发现 polyfill 没有效果，只能说明你执行到出问题的那一行，运行时并没有 polyfill。

另外，你在 ISSUE 中提供的 **完整异常信息** 毫无没有意义，无法对定位问题产生任何帮助。

**Comment by Dafrok** [comment]
polyfill 是全局生效的，加在库里没有任何意义。如果你发现 polyfill 没有效果，只能说明你执行到出问题的那一行，运行时并没有 polyfill。

建议你阅读一下 https://www.w3.org/2001/tag/doc/polyfills/ ，了解 polyfill 是个什么东西，怎么工作的，为什么不需要整合在包中。

另外，你在 ISSUE 中提供的 **完整异常信息** 无法对定位问题产生任何帮助。

**Comment by wekerSnail** [comment]
报错信息
```
SyntaxError: Unexpected token =
    at Object.webpackJsonp../node_modules/_vue-baidu-map@0.21.11@vue-baidu-map/components/base/factory.js (http://192.168.4.127:8080/4.js:322:1)
    at __webpack_require__ (http://192.168.4.127:8080/app.js:708:30)
    at fn (http://192.168.4.127:8080/app.js:113:20)
    at eval (webpack-internal:///./node_modules/_vue-baidu-map@0.21.11@vue-baidu-map/components/base/util.js:1:67)
    at Object.webpackJsonp../node_modules/_vue-baidu-map@0.21.11@vue-baidu-map/components/base/util.js (http://192.168.4.127:8080/4.js:338:1)
    at __webpack_require__ (http://192.168.4.127:8080/app.js:708:30)
    at fn (http://192.168.4.127:8080/app.js:113:20)
    at eval (webpack-internal:///./node_modules/_vue-baidu-map@0.21.11@vue-baidu-map/components/base/bindEvent.js:2:67)
    at Object.webpackJsonp../node_modules/_vue-baidu-map@0.21.11@vue-baidu-map/components/base/bindEvent.js (http://192.168.4.127:8080/4.js:306:1)
    at __webpack_require__ (http://192.168.4.127:8080/app.js:708:30)s.value @ vconsole.min.js?867d:11s.value @ vconsole.min.js?867d:11s.value @ vconsole.min.js?867d:11c.value @ vconsole.min.js?867d:11n.value @ vconsole.min.js?867d:11r.value @ vconsole.min.js?867d:10r.value @ vconsole.min.js?867d:10i @ vconsole.min.js?867d:10
vconsole.min.js?867d:11 [system] System: Unknown
```

**Comment by Dafrok** [comment]
等于号都抛错了，说明不是 polyfill 的问题，是 runtime 的问题，我推测你的组件根本就没有编译。

**Comment by Dafrok** [comment]
等于号都抛错了，说明不是 polyfill 的问题，是 runtime 的问题，我推测你的组件根本就没有编译成 es5。

**Comment by guidetheorient** [comment]
@wekerSnail @Dafrok 

同样android webview chrome/44遇到这个问题，试了全局引入`babel-polyfill`，结果无效 。所以，应该不是polyfill的问题

解决：在自己的项目中，配置babel-loader编译vue-baidu-map的文件。结果运行正常，可能是包的编译版本比较高的原因。

* vue-cli3
```
// vue.config.js 
module.exports = {
   transpileDependencies: [/vue-baidu-map/],
}
```

* vue-cli2
应该在webpack中js的rule中include选项中加入`vue-baidu-map`

**Comment by Dafrok** [comment]
谢谢楼上补充说明
