### ISSUE TITLE
nuxt下使用BmlMarkerClusterer出错

### ISSUE THREAD

**Issue by fengchangfight** [Dafrok/vue-baidu-map#502]
### 浏览器版本号

chrome  69.0.3497.100

### Vue 版本号

2.9.2

### 组件库版本号

0.21.11

### 现象描述

```
用nuxt plugin全局注册组件的方式注册BmlMarkerClusterer，npm run dev运行的情况下没问题，但是npm run build(npm start)的方式后，页面会有个问题，就是不能刷新页面，会报错。目前只发现这个组件有问题，其他组件如BmMarker都正常，并且是用同样的方式引入程序的
```

### 完整异常信息

```
app.4433419e1fc8e41f7a37.js:1 [nuxt] Error while initializing app DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (http://localhost:8043/_nuxt/vendor.ca9c67d328aaa9eb6b47.js:2:42712)
    at h (http://localhost:8043/_nuxt/vendor.ca9c67d328aaa9eb6b47.js:2:54861)
    at d (http://localhost:8043/_nuxt/vendor.ca9c67d328aaa9eb6b47.js:2:54495)
    at a.__patch__ (http://localhost:8043/_nuxt/vendor.ca9c67d328aaa9eb6b47.js:2:58440)
    at a.e._update (http://localhost:8043/_nuxt/vendor.ca9c67d328aaa9eb6b47.js:2:36595)
    at a.<anonymous> (http://localhost:8043/_nuxt/vendor.ca9c67d328aaa9eb6b47.js:2:65800)
    at $t.get (http://localhost:8043/_nuxt/vendor.ca9c67d328aaa9eb6b47.js:2:20903)
    at new $t (http://localhost:8043/_nuxt/vendor.ca9c67d328aaa9eb6b47.js:2:20821)
    at e (http://localhost:8043/_nuxt/vendor.ca9c67d328aaa9eb6b47.js:2:65778)
    at a.fn.$mount (http://localhost:8043/_nuxt/vendor.ca9c67d328aaa9eb6b47.js:2:65892)

```

### 在线示例 / 仓库 URL

https://github.com/fengchangfight/map-memory/blob/master/map-memory-frontend/pages/working/index.vue

### 复现用例

```
使用nuxt.js，全局引入BmlMarkerClusterer组件，npm run build之后，刷新页面，报错
```

### 预期输出

```
正常使用nuxt全局引入并可以正常刷新页面
```

### 实际输出

```
报错
```

**Comment by fengchangfight** [comment]
nuxt.js这个框架用得很蛋疼，但是现在已经入坑了，暂时不方便换 ，哪怕有个临时的workaround解决一下问题也行，问题是全局注册和局部注册的方式都试过了，没用，不知道这个BmlMarkerClusterer的实现方式有什么bug

**Comment by Dafrok** [comment]
你看下 appendChild 是哪里的逻辑

**Comment by fengchangfight** [comment]
@Dafrok 我换了个NUXt版本，用了个新的模板

**Comment by Dafrok** [comment]
@fengchangfight 解决了？我怀疑第三方开源库在某个生命周期里调用了 DOM API 导致的

**Comment by fengchangfight** [comment]
@Dafrok 嗯，解决了

**Comment by Dafrok** [comment]
OK
